python 非常的简单  
灵活的数据结构和类方法，让python的代码具有很高的效率  
在运行下面例子时，请在命令行中运行 conda install numpy 或者 pip install numpy  
下面是一个简单的输出例子  

In [2]:
print('hello world')

hello world


能够很容易的进行运算

In [3]:
print('1+1',1+2)
print('1-2',1-2)
print('1*2',1*2)
print('1/2',1/2)
print('1^2',1**2)

1+1 3
1-2 -1
1*2 2
1/2 0.5
1^2 1


最基本的数据类型有:float, int, str, list [] ; dict{}; set () 等  
list 表示列表，将每个元素线性地存起来  
dict是字典，存储形式为：{key值: value}  
set是集合，和列表类似，但在类方法上有区别  

In [4]:
print('int',1)
print('float',1.1)
print('str','abc')
print('list',[1,2,3,4,5])
print('dict',{1:2,3:'a'})
print('set',(1,2,35))

int 1
float 1.1
str abc
list [1, 2, 3, 4, 5]
dict {1: 2, 3: 'a'}
set (1, 2, 35)


list和set类似，可以用角标索引

In [5]:
L=[1,2,3]
S=(5,6,7)
print('L[1]:',L[1])
print('L[1]:',S[1])

L[1]: 2
L[1]: 6


dict 可以通过key值索引

In [6]:
D = {'a':1, 2:'b'}
print('D[\'a\']',D['a'])
print('D[2]',D[2])

D['a'] 1
D[2] b


if进行逻辑判断

In [7]:
if 1 > 5:
    print('1 > 5')
else:
    print('1 < 5')

1 < 5


for xx in xxx: 进行循环

In [8]:
print('in list')
for i in [1,3,5]:
    print(i)

print('\n in range')
for i in range(5):
    print(i)

in list
1
3
5

 in range
0
1
2
3
4


还有很多的库(numpy)，可以使用import 进行库导入， as则是对导入的模块或函数（类）取一个别名  
下面使用numpy中的random模块中的rand函数生成一个3X3的随机数数组

In [9]:
import numpy as np

a = np.random.rand(3,3)
print(a)
print(a[0][0],a[2,0])

[[0.62129043 0.19281429 0.5931692 ]
 [0.49800514 0.83341265 0.03616261]
 [0.4533254  0.29268953 0.17474526]]
0.6212904270810194 0.45332540362407825


numpy 是我们最经常使用的科学计算库，其最基本的的数据类型就是ndarray，
对于刚才生成数组a，它的数据类型dtype，形状shape和大小size如下

In [10]:
print(a.dtype, a.shape, a.size)

float64 (3, 3) 9


可以很方便的进行一些数学运算

In [11]:
print('a*a',a*a)

a*a [[0.38600179 0.03717735 0.3518497 ]
 [0.24800912 0.69457665 0.00130773]
 [0.20550392 0.08566716 0.03053591]]


python里面的函数
我们定一个加法函数

In [12]:
def plus(a,b):
    return a+b

print(plus(1,2))

3


定一个更加复杂的加法函数   
这个函数要通过输入来控制是否打印结果   
默认情况下是不打印的（isPrint=False）   
实际上，在python中，函数的参数可以分为两类：  
1，必备参数（a，b）  
2, 关键词参数（isPrint）  
必备参数没有默认值，比如输入，依赖于输入的顺序  
关键词参数有默认值，可以不输入，依赖于给定的关键词  

In [13]:
def plus(a, b, isPrint=False):
    res= a+b
    if isPrint:
        print('res = %f'%res)
    return res

res=plus(1,2,isPrint=True)

res = 3.000000


实现多数加法     
我们可以通过*argv将不确定个数的必备参数转化为一个与列表类似的东西  
存储在argv中，下面例子中首先将argv的内容 打印出来  
我们可以通过处理argv来得到多数相加  

In [15]:
def plus(*argv):
    print(argv)
    res  = 0
    for tmp in argv:
        res+=tmp
    return res

print(plus(1,2,3))

(1, 2, 3)
6


是多数加法的同时，控制是否print   
**kwargs则是将关键词参数转化为字典
我们也是将关键词参数打印出来  
通过处理字典的内容，我们可以完成控制是否print的需求

In [16]:
def plus(*argv,**kwargs):
    print(argv)
    print(kwargs)
    res  = 0
    for tmp in argv:
        res+=tmp
    if 'isPrint' in kwargs:
        if kwargs['isPrint']:
            print('res = %f'%res)
    return res

res=plus(1,2,3,isPrint=True)

(1, 2, 3)
{'isPrint': True}
res = 6.000000


python 里面有很多类  
我们定义一个简单的台网类Net和台站类Sta  
他们只包含最简答的属性name  
调用 getName则会放回这个属性  
类中间的self表示实例化的类所表示的对象  
self.xx = yy 相当于在对象内部生成一个指针，指向yy   
我们引用self.xx所得到的值就是yy  

In [17]:
class Net:
    def __init__(self,name='XA'):
        self.name=name
        
    def getName(self):
        return self.name

class Sta:
    def __init__(self,name='N01'):
        self.name=name
        
    def getName(self):
        return self.name 

我们可以实例化一个Net和一个Sta对象，  
在下面这个例子里，net是实例化后的Net,   
对于net这个对象，类函数中的self就表示net  
self.name 和 net.name 等价  

In [18]:
net = Net(name='XA')
sta = Sta(name='N01')
print(net.name, net.getName())
print(sta.name, sta.getName())

XA XA
N01 N01


我们在写一个类的时候，当它的部分功能和已有的类重合时，可以采用继承的方式来减少代码量，  
提高代码复用率  
比如，我们想用Net类来存储其中包含的Sta，那么就可以用到list这个类的某些方法，  
我们就可以从list这个类中继承一部分  

In [19]:
class Net(list):
    def __init__(self, staList=[], name='XA'):
        super().__init__(staList)
        self.name=name
    def getName(self):
        return self.name

我们通过指定Net的父类为list，继承了list的基本方法  
但是在初始化的时候，我们需要指定Net的名称  
于是，我们通过super().\__init\__()，继承list的初始化方法，并添加  
self.name=name对初始化方法进行了扩充  
在下面示例中，我们将三个Sta（sta1，sta2， sta3）对象存储到了Net对象net中  
里面net[i]的形式，可以对这些台站进行索引  

In [20]:
sta1 = Sta(name='N01')
sta2 = Sta(name='N02')
sta3 = Sta(name='N03')

net = Net([sta1,sta2,sta3],name='XA')
print('net name',net.getName())
print('net', net)
for i in range(3):
    print('sta %d :  %s'%(i, net[i].getName()))

net name XA
net [<__main__.Sta object at 0x10a1fbf28>, <__main__.Sta object at 0x10a1fbef0>, <__main__.Sta object at 0x10a1fbf60>]
sta 0 :  N01
sta 1 :  N02
sta 2 :  N03
